<h2>
    各情報を入力してください。
</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">
            Name
        </label>

        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">
            E-Mail
        </label>

        <!-- <?php echo $this->tag->textField("email"); ?> -->
        <!-- mailアドレスのみ -->
        <?php echo $this->tag->emailField("email"); ?>
    </p>



    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>